{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Fast_turtle Teleop Demo bug2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Important!\n",
    "\n",
    "To be able to run this notebook we need to run another notebook first:\n",
    "    <br>-> Click [here](Load_sim_fastturtle.ipynb) to open the notebook that launches the simulator (Fast Turtle)!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This example uses an algorithm called bug2. With this algorithm we can choose a final location, in the form of x and y coordinates, for the turtlebot.\n",
    "\n",
    "For this example we use the Fast Tutle simulator instead of the gazebo, which we used previously.\n",
    "\n",
    "In this example, the notebook publishes speed commands to the topic \"cmd_vel0\" to which the simulator is subscribed. Meanwhile, the notebook is subcribed to the topic \"robots\" in which the Fast Turtle simulator publishes information about the position and surroundings of the robot in real time.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import math\n",
    "import bqplot as bq\n",
    "import ipywidgets as wd\n",
    "import sys\n",
    "import sys\n",
    "from ipywidgets import interact, IntSlider, Layout, Button, Box, FloatText, Label, Dropdown, HBox, VBox, FloatSlider"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'RobotData'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_7628/2279134276.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mstd_msgs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmsg\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mString\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpath\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'/home/carolina/catkin_ws/src/fast_turtle/msg'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mRobotData\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mRobotDataArray\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mrospy\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[0;31m#importar o robotdataarray.msg para aqui, porque e la que esta escrito como e que a mensagem esta publicada no topico\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'RobotData'"
     ]
    }
   ],
   "source": [
    "from geometry_msgs.msg import Twist\n",
    "from nav_msgs.msg import Odometry\n",
    "from sensor_msgs.msg import LaserScan\n",
    "from std_msgs.msg import String\n",
    "sys.path.append('/home/carolina/catkin_ws/src/fast_turtle/msg')\n",
    "import RobotData, RobotDataArray\n",
    "import rospy  \n",
    "#importar o robotdataarray.msg para aqui, porque e la que esta escrito como e que a mensagem esta publicada no topico\n",
    "\n",
    "rospy.init_node('commander')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import jupyros"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def chamada(msg):\n",
    "    x = msg.robots[0].pose.position.x\n",
    "    y = msg.robots[0].pose.position.y\n",
    "    print(\"valor inicial de x: \",x, \", valor inicial de y: \", y)\n",
    "    sub.unregister()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] [1631043176.202771]: Publisher connected /cmd_vel0\n"
     ]
    }
   ],
   "source": [
    "# Sliders to control velocity\n",
    "linear_slider = FloatSlider(min = -1, max = 1, step = 0.05)\n",
    "angular_slider = FloatSlider(min = -1, max = 1, step = 0.1)\n",
    "\n",
    "pub = rospy.Publisher('/cmd_vel0', Twist, queue_size=10)\n",
    "rospy.loginfo(\"Publisher connected /cmd_vel0\")\n",
    "#sub = rospy.Subscriber(\"robots\", RobotDataArray, chamada)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "8e6bce5574fe4f3fa72443086c398b22",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Output(layout=Layout(border='1px solid gray'))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%%thread_cell\n",
    "\n",
    "rate = rospy.Rate(5)\n",
    "while True:\n",
    "    msg = Twist()\n",
    "    msg.linear.x = linear_slider.value\n",
    "    msg.angular.z = angular_slider.value\n",
    "    pub.publish(msg)\n",
    "    rate.sleep()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Control form\n",
    "controls = [ Box([Label(value=\"Linear\"), linear_slider]), Box([Label(value=\"Angular\"), angular_slider])]\n",
    "\n",
    "form = Box(controls, layout=Layout(\n",
    "    display='flex',\n",
    "    flex_flow='column',\n",
    "    border='solid 2px',\n",
    "    align_items='stretch',\n",
    "    padding='10px'\n",
    "))\n",
    "\n",
    "#form"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] [1631043176.930285]: Subscribed to /robots\n"
     ]
    }
   ],
   "source": [
    "# Live ploting of velocity or position\n",
    "x_sc = bq.LinearScale()\n",
    "y_sc = bq.LinearScale()\n",
    "\n",
    "ax_x = bq.Axis(label='X', scale=x_sc, grid_lines='solid')\n",
    "ax_y = bq.Axis(label='Y', scale=y_sc, orientation='vertical', grid_lines='solid')\n",
    "\n",
    "lines = bq.Lines(x=np.array([]), y=np.array([]), scales={'x': x_sc, 'y': y_sc})\n",
    "fig = bq.Figure(axes=[ax_x, ax_y], marks=[lines], labels=[\"linear\",\"angular\"], display_legend=True, title=\"Position\")\n",
    "data = []\n",
    "\n",
    "def cb(msg, data=data):\n",
    "    data.append([msg.robots[0].pose.position.x, msg.robots[0].pose.position.y])\n",
    "    data = data[-100:]\n",
    "    ndat = np.asarray(data).T\n",
    "    \n",
    "    if lines:\n",
    "        lines.y = ndat\n",
    "        lines.x = np.arange(len(data))\n",
    "\n",
    "rospy.Subscriber('/robots', RobotDataArray, cb)\n",
    "rospy.loginfo(\"Subscribed to /robots\")\n",
    "#fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1631043177.047852]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.067276]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "40c60fbad48141efb59adb59ba3db775",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Box(children=(Box(children=(Label(value='Linear'), FloatSlider(value=0.0, max=1.0, min=-1.0, step=0.05))), Boxâ€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1631043177.115609]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "form"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1631043177.147205]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.165919]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.210279]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.230745]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c21365e804b04871a9b9ee93a8d0efdb",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Figure(axes=[Axis(label='X', scale=LinearScale()), Axis(label='Y', orientation='vertical', scale=LinearScale()â€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR] [1631043177.263278]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.291757]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.321826]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.349856]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.355903]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.399644]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.422727]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.446741]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.455296]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.495668]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.505330]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.535689]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.558708]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.576624]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.611289]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.616987]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.637493]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.649951]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.667129]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.680222]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.703871]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.714581]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.761994]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.768036]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.839752]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.869607]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.888440]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.921172]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.932346]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.951295]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.967449]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.973506]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043177.994544]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.004960]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.042539]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.094684]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.100569]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.134614]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.144905]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.178875]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.183748]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.222395]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.226426]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.266303]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.275896]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.313900]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.358436]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.362096]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.402194]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.409667]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.446887]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.453814]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.494396]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.502817]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.542071]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.589408]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.593263]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.630125]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.633605]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.675236]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.678725]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.718787]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.724429]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.762010]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.806426]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.810386]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.850351]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.853379]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.894025]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.899144]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.938061]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.982163]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043178.985533]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.026555]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.030757]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.070262]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.073833]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.114642]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.160568]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.163717]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.206542]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.210153]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.255300]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.259544]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.302852]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.405212]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.422700]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.444453]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.455559]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.480658]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.517382]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.540479]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.553401]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.563811]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.585297]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.600571]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.617350]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.646627]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.690465]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.697739]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.739417]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.745932]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.783121]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.787922]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.866182]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.874063]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.902188]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.924052]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n",
      "[ERROR] [1631043179.939903]: bad callback: <function cb at 0x7fd6388f6d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joaoc/mambaforge/envs/robostackenv/lib/python3.8/site-packages/rospy/topics.py\", line 750, in _invoke_callback\n",
      "    cb(msg)\n",
      "  File \"/tmp/ipykernel_5564/1939566939.py\", line 13, in cb\n",
      "    data.append([msg.robots.pose.position.x, msg.robots.pose.position.y])\n",
      "AttributeError: 'list' object has no attribute 'pose'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
